Fix error handling for package version retrieval

diff --git a/.github/workflows/clean-packages.yml b/.github/workflows/clean-packages.yml
--- a/.github/workflows/clean-packages.yml
+++ b/.github/workflows/clean-packages.yml
@@ -249,9 +249,12 @@ jobs:
           PACKAGES_URL+="packages/container/${ENCODED_PACKAGE}/versions"
           echo "$PACKAGES_URL"
 
-          PACKAGES_JSON=$(gh api \
+          if ! PACKAGES_JSON=$(gh api \
             -H "Accept: application/vnd.github+json" \
-            -H "X-GitHub-Api-Version: 2022-11-28" ${PACKAGES_URL} || echo "")
+            -H "X-GitHub-Api-Version: 2022-11-28" ${PACKAGES_URL} || echo ""); then
+            echo "Unable to retrieve package versions"
+            exit 1
+          fi
           echo "$PACKAGES_JSON"
 
           # If list of package versions does not exist just fail
